# -*- coding: utf-8 -*-
"""assignment3 array rotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wxw-mVCAGUH8zMVB_TbetfTnnDIqnE5f
"""

#rotate array
array = [1,2,3,4,5]
shift = 3 #no of times the array rotates
for i in range(0,shift):
  temp = array[0]
  for j in range(0,len(array)-1):
    array[j] = array [j+1]
  array[len(array)-1] = temp
for i in range(0,len(array)):
  print(array[i])

#rotate array 2
import random
def var01(A,x):
  B = [0]*len(A)
  y = x
  r = 0
  for j in range(0,x):
    B[j] = A[len(A)-y]
    y -= 1
  for g in range(x,len(A)):
    B[g] = A[r]
    r += 1
  print(B)

A = [0]*10
for i in range(0,10):
  A[i] = random.randrange(50)
print(A)
x = int(input("Enter the number:"))
var01(A,x)

#rotate array 3
import random
def var(z,o):
  x = 0
  for g in range(0,o):
    x = z[-1]
    for j in range(2,len(z)+1):
      z[-j+1] = z[-j]
    z[0] = x
  return print(z)
A = [0]*10
for i in range(0,10):
  A[i] = random.randrange(50)
print(A)
o =int(input("Enter the number you wanna shift :"))
var(A,o)

