# -*- coding: utf-8 -*-
"""complexity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fvs805P9STOlQJg7htDxVgFXOSQAtBK8
"""

#complexity O(n)
#fill the array
import random 
F=[0]*10
for i in range(0,10):
  F[i]=random.randrange(10)
print(F)
#searching in array for maximum value
x=F[0]
for i in range(1,len(F)):
  if (x<F[i]):
    x=F[i]
print(f"maximum f in array is = {x}")
print("maximum f in array is = ",x)

#does array has a duplicate?
import random
def hasDuplicate(A):
  for i in range(0,len(A)):
    for j in range(0,len(A)):
      if(i==j):
        continue
      if(A[i]==A[j]):
        return True,A[i]
  return False
A=[0]*10
for i in range(0,10):
  A[i]=random.randrange(50)
print(A)
print(f"{has Duplicate(A)}")