# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZHQtYBXcjZqEqeo5vhmRvJ3KiRJIA71
"""

a=5
print (a)

print(a)





import math
math.exp(4)



variable = 2

for i in range(0,5):
  variable  = variable * 2
  print (variable)

variable = 2
buffervariable=variable
for i in range(0,9):
  buffervariable = variable*2
print (buffervariable)

name=str(input("what is your name ?"))
age=int(input("what is your age?"))
print("Your name is ",name)
print("your age is ",age)

import math
r=float(input("type the radius:"))
Area = math.pi*r*r
print ("the area of circle is ",Area)

a=float(input("enter the first number A "))
b=float(input("enter the second number B"))
a1=int(input("Press 1 for addition \nPress2 for subtraction\nPress 3 for multiplication\nPress 4 for division"))
if(a1==1):
  print((a+b))
elif(a1==2):
  a=int(a-b)
  print(a)
elif(a1==3):
  a=int(a*b)
  print(a)
elif(a1==4):
  if(b!=0):
    a=a/b
    print(a)
  else:
    print("the number is not divisible")

#factorial
x=int(input("enter the number"))
y=1
for i in range(0,x-1):
  y=y*x-1
print(y)



#to inverse the number
a=int(input("Enter the number:"))
f=""
while (a%10!=0):
  b=a%10
  print(b)
  f=f+str(b)
  a=int(a/10)
print(int(f))

#print the sum of the digits
a=int(input("enter the number:"))
f=0
while(a%10!=0):
  b=a%10
  f=f+b
  a=int(a/10)
print(int(f))

#inverse number2
a=a1=int(input("Enter the number you want to reverse="))
f=0
while(a>0):
  b=a%10
  f=f*10+b
  a=int(a/10)
print("inverse of ",a1," is = ", int(f))

#fibonocci
a=int(input("Enter the number = "))
n=0
n1=1
c=a
for i in range(1,abs(a)):
  c=n+n1
  n1=c
if(a<0):
   c=abs(c)*pow(-1,a+1)
print("Fibonacci of ",a,"is = ",int(c))

#complexity